Algoritmo "Circulo"
// Escreva o programa capaz de ler o valor "r" do raio de um circulo e
// mostre o valor da área do círculo com três casas decimais.
// A fórmula da área do círculo é a seguinte:
// area = pi.r².
// Você pode usar o pi fornecido pela bilbioteca da sua linguagem, ou
// o valor 3.14159

Var
   preco_produto, valor_recebido, troco : real
   qtd_produto : inteiro
   
Inicio


Fimalgoritmo